name: project3_test

on:
  push:
    branches:
      - '**'
    tags:
      - '**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          pip install poetry
          make install
